In [1]:
from google.colab import files 
files = files.upload()

Saving sorted_final.csv to sorted_final (1).csv


In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv("sorted_final.csv", index_col = 0)

In [34]:
df

Station Names  YEAR  ...     Boro_Area  Boro_Production
0          Barisal  1970  ...           NaN              NaN
1            Bhola  1970  ...           NaN              NaN
2            Bogra  1970  ...  3.032000e+04       20574.9558
3         Chandpur  1970  ...           NaN              NaN
4       Chittagong  1970  ...  1.434810e+05      147662.5025
...            ...   ...  ...           ...              ...
1521     Srimongal  2018  ...           NaN              NaN
1522       Syedpur  2018  ...           NaN              NaN
1523        Sylhet  2018  ...  4.269926e+05      241039.0000
1524       Tangail  2018  ...  1.025890e+06      840931.0000
1525        Teknaf  2018  ...           NaN              NaN

[1561 rows x 15 columns]

In [35]:
def avg_temp(df):
  df['Average_temperature'] = df[['Max Temp', 'Min Temp']].mean(axis=1)
  return df

In [36]:
df = avg_temp(df)

In [37]:
df = df.interpolate(method = 'linear', limit =2)
df_new = df.fillna(method = 'bfill',limit = 2)
df_new2 = df_new.fillna(method = 'ffill',limit =2)
#df_new2.dropna(axis = 0, inplace = True)

In [38]:
df_new2.isnull().sum()

Station Names          0
YEAR                   0
Max Temp               0
Min Temp               0
Rainfall               0
Relative Humidity      0
Wind Speed             0
Cloud Coverage         0
Bright Sunshine        0
Aus_Area               0
Aus_Production         0
Amon_Area              0
Amon_Production        0
Boro_Area              0
Boro_Production        0
Average_temperature    0
dtype: int64

In [39]:
aus_avg = df_new2[['Station Names','YEAR','Average_temperature','Rainfall','Relative Humidity','Wind Speed','Cloud Coverage','Bright Sunshine','Aus_Area','Aus_Production']]

In [40]:
amon_avg = df_new2[['Station Names','YEAR','Average_temperature','Rainfall','Relative Humidity','Wind Speed','Cloud Coverage','Bright Sunshine','Amon_Area','Amon_Production']]

In [41]:
boro_avg = df_new2[['Station Names','YEAR','Average_temperature','Rainfall','Relative Humidity','Wind Speed','Cloud Coverage','Bright Sunshine','Boro_Area','Boro_Production']]

In [42]:
# AUS
x = aus_avg.drop('Aus_Production',axis =1)
y = aus_avg['Aus_Production']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 23)
# AMON
x_amon = amon_avg.drop('Amon_Production',axis =1)
y_amon = amon_avg['Amon_Production']
x_amon_train, x_amon_test, y_amon_train, y_amon_test = train_test_split(x_amon, y_amon, test_size = 0.20, random_state = 23)
# BORO
x_boro = boro_avg.drop('Boro_Production',axis =1)
y_boro = boro_avg['Boro_Production']
x_boro_train, x_boro_test, y_boro_train, y_boro_test = train_test_split(x_boro, y_boro, test_size = 0.20, random_state = 23)

In [43]:
xx_test = xx_test.copy()
x_amons_test = x_amons_test.copy()
x_boros_test = x_boros_test.copy()

In [44]:
le = LabelEncoder()
x_train['Station Names'] = le.fit_transform(x_train[['Station Names']])
x_test['Station Names'] = le.fit_transform(x_test[['Station Names']])

x_amon_train['Station Names'] = le.fit_transform(x_amon_train[['Station Names']])
x_amon_test['Station Names'] = le.fit_transform(x_amon_test[['Station Names']])

x_boro_train['Station Names'] = le.fit_transform(x_boro_train[['Station Names']])
x_boro_test['Station Names'] = le.fit_transform(x_boro_test[['Station Names']])

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [45]:
x_boro_test

Station Names  YEAR  ...  Bright Sunshine      Boro_Area
679              32  1998  ...         3.683333  692373.333333
768              30  2000  ...         3.630833  801070.000000
182              13  1984  ...         2.965000   97285.000000
1072             23  1973  ...         6.355655  117085.000000
474              31  1992  ...         3.205000  545133.333333
...             ...   ...  ...              ...            ...
871              31  2003  ...         6.533333  836416.666667
433              22  1991  ...         5.491667  262890.000000
52               35  1979  ...         3.512500  332820.000000
955              11  2006  ...         3.755000  597595.000000
570               1  1995  ...         6.535897  124750.000000

[313 rows x 9 columns]

In [46]:
## StandardScaler


In [47]:
from sklearn.preprocessing import StandardScaler
Scaler = StandardScaler()
Scaler.fit(x_boro_train)
x_boro_trainScaled = Scaler.transform(x_boro_train)

In [48]:
Scaler.fit(x_boro_test)
x_boro_testScaled = Scaler.transform(x_boro_test)
x_boro_testScaled

array([[ 1.32581792,  0.1819022 ,  0.38344737, ...,  0.40649806,
        -0.29770575,  2.0948764 ],
       [ 1.12970213,  0.3294032 , -1.66051827, ...,  0.278187  ,
        -0.34324926,  2.62305795],
       [-0.53728207, -0.85060484, -0.77328065, ..., -1.34912311,
        -0.92085661, -0.79679162],
       ...,
       [ 1.6199916 , -1.21935735, -0.06784994, ..., -0.01102205,
        -0.44590288,  0.34772591],
       [-0.73339786,  0.77190622,  0.81492921, ...,  0.58165285,
        -0.23553525,  1.63432717],
       [-1.7139768 , -0.03934931,  2.68204178, ..., -0.10267281,
         2.17688047, -0.663333  ]])

In [49]:
Scaler = StandardScaler()
Scaler.fit(x_amon_train)
x_amon_trainScaled = Scaler.transform(x_amon_train)

In [50]:
Scaler.fit(x_amon_test)
x_amon_testScaled = Scaler.transform(x_amon_test)
x_amon_testScaled

array([[ 1.32581792,  0.1819022 ,  0.38344737, ...,  0.40649806,
        -0.29770575,  1.63240532],
       [ 1.12970213,  0.3294032 , -1.66051827, ...,  0.278187  ,
        -0.34324926,  2.39222808],
       [-0.53728207, -0.85060484, -0.77328065, ..., -1.34912311,
        -0.92085661,  0.13953353],
       ...,
       [ 1.6199916 , -1.21935735, -0.06784994, ..., -0.01102205,
        -0.44590288,  0.95430463],
       [-0.73339786,  0.77190622,  0.81492921, ...,  0.58165285,
        -0.23553525, -0.61790102],
       [-1.7139768 , -0.03934931,  2.68204178, ..., -0.10267281,
         2.17688047,  0.20407317]])

In [51]:
Scaler = StandardScaler()
Scaler.fit(x_train)
x_trainScaled = Scaler.transform(x_train)

In [52]:
Scaler.fit(x_test)
x_testScaled = Scaler.transform(x_test)
x_testScaled

array([[ 1.32581792,  0.1819022 ,  0.38344737, ...,  0.40649806,
        -0.29770575,  0.64271435],
       [ 1.12970213,  0.3294032 , -1.66051827, ...,  0.278187  ,
        -0.34324926, -0.92087801],
       [-0.53728207, -0.85060484, -0.77328065, ..., -1.34912311,
        -0.92085661,  1.68633993],
       ...,
       [ 1.6199916 , -1.21935735, -0.06784994, ..., -0.01102205,
        -0.44590288,  1.00180351],
       [-0.73339786,  0.77190622,  0.81492921, ...,  0.58165285,
        -0.23553525, -0.9764152 ],
       [-1.7139768 , -0.03934931,  2.68204178, ..., -0.10267281,
         2.17688047,  0.32422447]])

In [87]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.metrics import r2_score
rf_model= RandomForestRegressor(criterion='squared_error',max_depth=120,max_features='auto',min_samples_leaf=2,min_samples_split=5,n_estimators=1600)
rf_model.fit(x_trainScaled, y_train)

predict_with_regressor = rf_model.predict(x_testScaled)

mse_regressor = mean_squared_error(y_test, predict_with_regressor)
mae_regressor = mean_absolute_error(y_test, predict_with_regressor)
print("mean squared error for Randomforest= ",mse_regressor)
print("mean absoluate error for Randomforest= ",mae_regressor)


accuracy = r2_score(y_test,predict_with_regressor)
print(accuracy*100)

mean squared error for Randomforest=  313856306.1020566
mean absoluate error for Randomforest=  12382.100251703794
92.47304992342539


In [ ]:
# fill missing value with interpluate data set
mean squared error for Randomforest=  674505443.1689728
mean absoluate error for Randomforest=  15681.988628119523
85.84790934244371

SyntaxError: ignored

In [89]:
rf_model_amon= RandomForestRegressor(criterion='squared_error',max_depth=670,max_features='auto',min_samples_leaf=1,min_samples_split =2,n_estimators = 600)
rf_model_amon.fit(x_amon_trainScaled, y_amon_train)

predict_with_regressor = rf_model_amon.predict(x_amon_testScaled)

mse_regressor = mean_squared_error(y_amon_test, predict_with_regressor)
mae_regressor = mean_absolute_error(y_amon_test, predict_with_regressor)
print("mean squared error for Randomforest= ",mse_regressor)
print("mean absoluate error for Randomforest= ",mae_regressor)


accuracy = r2_score(y_amon_test,predict_with_regressor)
print(accuracy*100)

mean squared error for Randomforest=  2859510102.001987
mean absoluate error for Randomforest=  34419.90714427038
91.8717167341243


In [91]:
rf_model_boro= RandomForestRegressor()
rf_model_boro.fit(x_boro_trainScaled, y_boro_train)

predict_with_regressor = rf_model_boro.predict(x_boro_testScaled)

mse_regressor = mean_squared_error(y_boro_test, predict_with_regressor)
mae_regressor = mean_absolute_error(y_boro_test, predict_with_regressor)
print("mean squared error for Randomforest= ",mse_regressor)
print("mean absoluate error for Randomforest= ",mae_regressor)


accuracy = r2_score(y_boro_test,predict_with_regressor)
print(accuracy*100)

mean squared error for Randomforest=  2273776558.0752892
mean absoluate error for Randomforest=  36079.670153754705
95.46189125555807


In [ ]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV

n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]

max_features = ['auto', 'sqrt','log2']

max_depth = [int(x) for x in np.linspace(10, 1000,10)]

min_samples_split = [2, 5, 10,14]

min_samples_leaf = [1, 2, 4,6,8]

random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['squared_error']}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['squared_error']}


In [ ]:
model=RandomForestRegressor()
model_randomcv=RandomizedSearchCV(estimator=model,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                               random_state=100,n_jobs=-1)
### fit the randomized model
boro = model_randomcv.fit(x_boro_train,y_boro_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


In [ ]:
model=RandomForestRegressor()
model_randomcv=RandomizedSearchCV(estimator=model,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                               random_state=100,n_jobs=-1)
### fit the randomized model
amon = model_randomcv.fit(x_amon_train,y_amon_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


In [ ]:
model=RandomForestRegressor()
model_randomcv=RandomizedSearchCV(estimator=model,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                               random_state=100,n_jobs=-1)
### fit the randomized model
aus = model_randomcv.fit(x_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


In [ ]:
boro.best_params_

{'criterion': 'squared_error',
 'max_depth': 890,
 'max_features': 'auto',
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'n_estimators': 600}

In [ ]:
amon.best_params_

{'criterion': 'squared_error',
 'max_depth': 670,
 'max_features': 'auto',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 600}

In [ ]:
aus.best_params_

{'criterion': 'squared_error',
 'max_depth': 120,
 'max_features': 'auto',
 'min_samples_leaf': 2,
 'min_samples_split': 5,
 'n_estimators': 1600}

In [ ]:

## building a predictive system

In [93]:
input_data_aus =(1.325818,0.181902,0.383447,-0.684030,-0.440520,-0.637928,0.406498,-0.297706,1.632405)
input_data_amon = (1.325818,0.181902,0.383447,-0.684030,-0.440520,-0.637928,0.406498,-0.297706,0.64271)
input_data_boro =(1.325818,0.181902,0.383447,-0.684030,-0.440520,-0.637928,0.406498,-0.297706,0.64271)
import numpy as np
input = np.array(input_data)
input_amon = np.array(input_data_amon)
input_boro = np.array(input_data_boro)
reshape = input.reshape(1,-1)
reshape1 = input_amon.reshape(1,-1)
reshape2 = input_boro.reshape(1,-1)
pred= rf_model.predict(reshape)
predA= rf_model_amon.predict(reshape1)
predB= rf_model_boro.predict(reshape2)
print("Aus_Predict_value",pred)
print("Aus_Actual_value",y_test.loc[[2]])
print("Amon_Predict_value",predA)
print("Amon_Actual_value",y_test.loc[[2]])
print("Boro_Predict_value",predB)
print("Boro_Actual_value",y_test.loc[[2]])

Aus_Predict_value [159557.31415941]
Aus_Actual_value 2    86400.2994
Name: Aus_Production, dtype: float64
Amon_Predict_value [484533.99945159]
Amon_Actual_value 2    86400.2994
Name: Aus_Production, dtype: float64
Boro_Predict_value [513813.6770428]
Boro_Actual_value 2    86400.2994
Name: Aus_Production, dtype: float64


In [69]:
x_testScaled[311]

array([-0.73339786,  0.77190622,  0.81492921, -0.47362423, -0.40906143,
       -0.73553943,  0.58165285, -0.23553525, -0.9764152 ])

In [57]:
pd.DataFrame(x_testScaled)

0         1         2  ...         6         7         8
0    1.325818  0.181902  0.383447  ...  0.406498 -0.297706  0.642714
1    1.129702  0.329403 -1.660518  ...  0.278187 -0.343249 -0.920878
2   -0.537282 -0.850605 -0.773281  ... -1.349123 -0.920857  1.686340
3    0.443297 -1.661860  0.383447  ... -0.754412  2.020521  1.501616
4    1.227760 -0.260601 -0.178817  ... -0.762558 -0.712658  0.713281
..        ...       ...       ...  ...       ...       ...       ...
308  1.227760  0.550655  1.206843  ... -0.537903  2.174656 -0.477382
309  0.345239 -0.334351  1.448529  ... -0.143406  1.271015  0.487510
310  1.619992 -1.219357 -0.067850  ... -0.011022 -0.445903  1.001804
311 -0.733398  0.771906  0.814929  ...  0.581653 -0.235535 -0.976415
312 -1.713977 -0.039349  2.682042  ... -0.102673  2.176880  0.324224

[313 rows x 9 columns]

In [81]:
pd.DataFrame(x_amon_testScaled)

0         1         2  ...         6         7         8
0    1.325818  0.181902  0.383447  ...  0.406498 -0.297706  1.632405
1    1.129702  0.329403 -1.660518  ...  0.278187 -0.343249  2.392228
2   -0.537282 -0.850605 -0.773281  ... -1.349123 -0.920857  0.139534
3    0.443297 -1.661860  0.383447  ... -0.754412  2.020521  1.091312
4    1.227760 -0.260601 -0.178817  ... -0.762558 -0.712658  2.111266
..        ...       ...       ...  ...       ...       ...       ...
308  1.227760  0.550655  1.206843  ... -0.537903  2.174656  1.977952
309  0.345239 -0.334351  1.448529  ... -0.143406  1.271015 -0.076679
310  1.619992 -1.219357 -0.067850  ... -0.011022 -0.445903  0.954305
311 -0.733398  0.771906  0.814929  ...  0.581653 -0.235535 -0.617901
312 -1.713977 -0.039349  2.682042  ... -0.102673  2.176880  0.204073

[313 rows x 9 columns]

In [82]:
pd.DataFrame(x_boro_testScaled)

0         1         2  ...         6         7         8
0    1.325818  0.181902  0.383447  ...  0.406498 -0.297706  2.094876
1    1.129702  0.329403 -1.660518  ...  0.278187 -0.343249  2.623058
2   -0.537282 -0.850605 -0.773281  ... -1.349123 -0.920857 -0.796792
3    0.443297 -1.661860  0.383447  ... -0.754412  2.020521 -0.700579
4    1.227760 -0.260601 -0.178817  ... -0.762558 -0.712658  1.379404
..        ...       ...       ...  ...       ...       ...       ...
308  1.227760  0.550655  1.206843  ... -0.537903  2.174656  2.794815
309  0.345239 -0.334351  1.448529  ... -0.143406  1.271015  0.007920
310  1.619992 -1.219357 -0.067850  ... -0.011022 -0.445903  0.347726
311 -0.733398  0.771906  0.814929  ...  0.581653 -0.235535  1.634327
312 -1.713977 -0.039349  2.682042  ... -0.102673  2.176880 -0.663333

[313 rows x 9 columns]